### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by matiasilva**

### CODE REVIEW

**Comment by edwinbalani** [comment]
In the interest of Britishness, shouldn't we call it `COPYING`?

**Comment by mas90** [comment]
> In the interest of Britishness, shouldn't we call it `COPYING`?

Or `LICENCE`? :-)

**Comment by edwinbalani** [comment]
I tend to use COPYING because UI auto-things to show the licence in use don't recognise LICENCE most of the time :(

**Comment by matiasilva** [comment]
Sadly, GH only recognizes LICENSE or COPYING (so MIT shows up as the repo license). I don't mind, but for consistency we should stick with LICENSE.

**Pull request merged**
