### PR TITLE
Use raw docker-compose when Getting Started

### PR DESCRIPTION
**Pull request by doismellburning**
I'm not entirely convinced of the correctness here.

It looks like the `manage.py` script assumes presence of `python` and a
variety of installed libraries, but essentially just wraps
docker-compose.

This commit replaces that instruction with a straight `docker-compose`
call, which solves the problem of the missing dependencies etc., but it
looks like the compose file isn't meant to be used directly, based on
the number of environment variables expected to be set.

So, this commit certainly improves the instructions in that (assuming
you have docker-compose installed) it starts up an instance of the
webapp correctly, but I suspect the environment variables I've skipped
over are important.

### CODE REVIEW

**Comment by CHTJonas** [comment]
I agree; the `manage.py` executable seems counter-productive and nullifies all the benefits of using Docker!

**Comment by CHTJonas** [comment]
Requesting review from @matiasilva who I believe was the one who created the Docker stuff.

**Comment by matiasilva** [comment]
The docker stuff was taken from a tutorial that @CHTJonas provided me with but I agree that I felt dirty using it. It essentially makes sure the environment vars are set with the compose call.

**Comment by matiasilva** [comment]
In light of the move to Makefiles shall we still go ahead with this one?

**Comment by doismellburning** [comment]
Fair; might as well?

**Pull request merged**
